# _config.yml
theme: minima
title: "FusionPilot"
description: "Documentation of a sensor fusion and obstacle avoidance project leveraging UCSD AVL lab resources and advanced integration techniques."
# You can add more configuration options (e.g., custom CSS) as needed.
header_pages:
  - roadmap.md
  - completed-work.md
  - videos.md